[[testcase]]
  [testcase.job]
    title = "Test 3"
    command = "/bin/date -u"
    groupName = "Test"
    schedule = "0 4 * * 1,2,3,4,5"  # every day at 4am on M-F
  [[testcase.test]]
    testtime = 2016-10-02T04:00:00
    expectedresult = false
  [[testcase.test]]
    testtime = 2016-10-04T04:00:00
    expectedresult = true

[[testcase]]
  [testcase.job]
    title = "Test 4"
    command = "/bin/date -u"
    groupName = "Test"
    schedule = "0 4 * * 1-5"  # every day at 4am on M-F
  [[testcase.test]]
    testtime = 2016-10-02T04:00:00
    expectedresult = false
  [[testcase.test]]
    testtime = 2016-10-04T04:00:00
    expectedresult = true
