[[job]]
title = "Check the UTC time"
command = "/bin/date -u"
groupName = "Test"
scheduleClassic = "* * * * *"
[job.schedule]
  [job.schedule.minute]
    isInterval = true
    interval = "1m"
    startTime = ["12:00AM"]
    endTime = "11:59PM"

