[[job]]
title = "Minutely"
exec = "echo 'minute'"
groupName = "Test"
schedule = "* * * * *"  # every minute

[[job]]
title = "Quarter Hourly"
exec = "echo 'qhour'"
groupName = "Test"
schedule = "*/15 * * * *"  # every qhour

[[job]]
title = "Hourly"
exec = "echo 'hour'"
groupName = "Test"
schedule = "0 * * * *"  # every hour

