[[job]]
title = "Minutely"
exec = "/sbin/ping -c 10 127.0.0.1"
groupName = "Test"
schedule = "* * * * *"  # every minute

[[job]]
title = "Quarter Hourly"
exec = "/sbin/ping -c 10 127.0.0.1"
groupName = "Test"
schedule = "*/15 * * * *"  # every qhour

[[job]]
title = "Hourly"
exec = "/sbin/ping -c 10 127.0.0.1"
groupName = "Test"
schedule = "0 * * * *"  # every hour

